figure(1)
plot(testtime, st)
figure(2)
plot(testtime, sh)
figure(3)
plot(testtime, sv)
figure(4)
plot(testtime, vt)
figure(5)
plot(testtime, vh)
figure(6)
plot(testtime, vv)
figure(7)
plot(testtime, ax)
figure(8)
plot(testtime, ay)
figure(9)
plot(testtime, az)